/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "tag2": {
      "key": "tag2",
      "scope": "tags",
      "path": "/tag/tag2/",
      "pageKeys": [
        "v-7e780878"
      ]
    },
    "tag3": {
      "key": "tag3",
      "scope": "tags",
      "path": "/tag/tag3/",
      "pageKeys": [
        "v-5e9dfbe4"
      ]
    },
    "tag1": {
      "key": "tag1",
      "scope": "tags",
      "path": "/tag/tag1/",
      "pageKeys": [
        "v-053d40f8"
      ]
    },
    "tag4": {
      "key": "tag4",
      "scope": "tags",
      "path": "/tag/tag4/",
      "pageKeys": [
        "v-22009824"
      ]
    }
  },
  "categories": {
    "category1": {
      "key": "category1",
      "scope": "categories",
      "path": "/categories/category1/",
      "pageKeys": [
        "v-7e780878",
        "v-053d40f8"
      ]
    },
    "category2": {
      "key": "category2",
      "scope": "categories",
      "path": "/categories/category2/",
      "pageKeys": [
        "v-5e9dfbe4",
        "v-22009824"
      ]
    }
  },
  "timeline": {}
}