name: 部署文档

on:
  push:
    branches: 
      - main  # 你的默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: 20
          cache: npm
          
      - name: 安装依赖
        run: npm install
 
      - name: 构建文档  # 构建 VuePress 网站
        run: npm run build
      
      - name: 部署文档
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: vuepress-reco/vuepress-reco.github.io
          target_branch: master
          build_dir: .vuepress
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
